### ISSUE TITLE
Video does not record: apq8084-common: Import camera wrapper from lentislte-common

### ISSUE THREAD

**Issue by ripee** [samsung-apq8084/android_device_samsung_apq8084-common#1]
In trlte, 3rd party camera apps are unable to save recorded video. The apps run just fine when recording is started and stopped, but they do not save any video file. Video files are only displayed as thumbnails and any attempt to play them back errors out, saying that the video file doesn't exist.

**Comment by github-cygwin** [comment]
Fortunately the camera wrapper changes are not affecting this problem.
I tracked this down to a kernel patch, https://review.lineageos.org/#/c/204122/
which I'm going to revert, https://review.lineageos.org/204397/

Thanks for reporting,
Corinna
